import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { apiGet } from "../lib/api";
import { ErrorState, LoadingState } from "./shared/RequestState";

// GET /reports/{token} — public, no auth. The read side of Recommend's
// "Share" button: a login-free snapshot of one past /recommend run,
// published explicitly by its owner (see /auth/me/history/{id}/share).
export default function Reports() {
  const { token } = useParams();
  const [state, setState] = useState({ status: "loading", data: null });

  useEffect(() => {
    apiGet(`/reports/${token}`).then(({ ok, data }) => {
      setState(ok ? { status: "ready", data } : { status: "error", data });
    });
  }, [token]);

  return (
    <section className="mx-auto max-w-3xl px-6 py-16">
      {state.status === "loading" && <LoadingState label="Loading shared report…" />}
      {state.status === "error" && <ErrorState message={state.data?.detail || "This shared link doesn't exist, or was revoked."} />}
      {state.status === "ready" && (
        <>
          <span className="font-sans text-xs font-semibold uppercase tracking-[0.25em] text-forest/60">Shared skill report</span>
          <h1 className="mt-2 font-display text-3xl font-bold capitalize text-charcoal sm:text-4xl">{state.data.target_role}</h1>
          <p className="mt-2 font-sans text-sm text-charcoal/50">
            Shared {new Date(state.data.shared_at).toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" })}
          </p>

          {state.data.skills_at_time?.length > 0 && (
            <div className="mt-6">
              <p className="font-sans text-[11px] font-semibold uppercase tracking-wide text-forest/50">Skills at the time</p>
              <div className="mt-2 flex flex-wrap gap-1.5">
                {state.data.skills_at_time.map((s) => (
                  <span key={s} className="rounded-full bg-periwinkle/30 px-2.5 py-0.5 text-xs text-charcoal">
                    {s}
                  </span>
                ))}
              </div>
            </div>
          )}

          <div className="mt-8 flex flex-col gap-3">
            {state.data.recommendations.map((rec, index) => (
              <div key={rec.skill} className="rounded-2xl border border-forest/10 bg-lime/10 p-5">
                <div className="flex items-center justify-between">
                  <span className="flex items-center gap-3">
                    <span className="flex h-7 w-7 items-center justify-center rounded-full bg-lime/40 font-display text-xs font-bold text-forest">
                      {index + 1}
                    </span>
                    <span className="font-display text-lg font-semibold text-charcoal">{rec.skill}</span>
                  </span>
                  <span className="font-sans text-xs text-charcoal/50">
                    {rec.postings_mentioning_it} posting{rec.postings_mentioning_it === 1 ? "" : "s"} mention it
                  </span>
                </div>
                {rec.evidence?.length > 0 && (
                  <div className="mt-3 flex flex-col gap-1.5 border-t border-forest/8 pt-3">
                    {rec.evidence.map((post, i) => (
                      <p key={i} className="font-sans text-xs text-charcoal/60">
                        <span className="font-medium text-charcoal/80">{post.title}</span> — {post.company ?? "Unknown"} · {post.location ?? "—"}
                      </p>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>

          <p className="mt-10 font-sans text-xs text-charcoal/40">
            Generated by NextSkill from real job-posting data. Create your own at nextskill's{" "}
            <a href="/recommend" className="font-semibold text-forest underline">
              Recommend
            </a>{" "}
            page.
          </p>
        </>
      )}
    </section>
  );
}
