"""sync schema with redesigned models

Revision ID: e9ad66fe31f3
Revises: ef8243d65c1c
Create Date: 2026-08-31 10:00:11.571182+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e9ad66fe31f3"
down_revision: Union[str, Sequence[str], None] = "ef8243d65c1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_skills", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("job_skills_skill_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("job_skills_job_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "jobs", ["job_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            None, "skills", ["skill_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("jobs_external_id_key"), type_="unique")
        batch_op.create_index("ix_jobs_company_id", ["company_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_jobs_external_id"), ["external_id"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_jobs_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_title"), ["title"], unique=False)
        batch_op.create_index("ix_jobs_title_source", ["title", "source"], unique=False)
        batch_op.drop_constraint(batch_op.f("jobs_company_id_fkey"), type_="foreignkey")
        batch_op.create_foreign_key(
            None, "companies", ["company_id"], ["id"], ondelete="SET NULL"
        )

    with op.batch_alter_table("recommendation_history", schema=None) as batch_op:
        batch_op.alter_column(
            "skills_at_time",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "recommendations",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
        )
        batch_op.drop_constraint(
            batch_op.f("recommendation_history_user_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "users", ["user_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("saved_jobs", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
        )
        batch_op.create_index(
            batch_op.f("ix_saved_jobs_job_id"), ["job_id"], unique=False
        )
        batch_op.drop_constraint(
            batch_op.f("saved_jobs_job_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("saved_jobs_user_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "jobs", ["job_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            None, "users", ["user_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("shared_reports", schema=None) as batch_op:
        batch_op.alter_column(
            "skills_at_time",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "recommendations",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
        )
        batch_op.drop_constraint(
            batch_op.f("shared_reports_user_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "users", ["user_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("skills_name_key"), type_="unique")
        batch_op.create_index(batch_op.f("ix_skills_name"), ["name"], unique=True)

    # Backfill existing rows created before this column had a default —
    # autogenerate only knows how to change the schema, not that a couple
    # of dev/test rows predate it and would violate the new NOT NULL.
    op.execute("UPDATE users SET created_at = now() WHERE created_at IS NULL")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "skills",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            server_default="[]",
            type_=postgresql.JSONB(astext_type=sa.Text()),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            type_=sa.DateTime(timezone=True),
            nullable=False,
        )
        batch_op.drop_constraint(batch_op.f("users_email_key"), type_="unique")
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.create_unique_constraint(
            batch_op.f("users_email_key"),
            ["email"],
            postgresql_nulls_not_distinct=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            server_default=None,
            type_=postgresql.TIMESTAMP(),
            nullable=True,
        )
        batch_op.alter_column(
            "skills",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            server_default=None,
            type_=postgresql.JSON(astext_type=sa.Text()),
            existing_nullable=False,
        )

    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skills_name"))
        batch_op.create_unique_constraint(
            batch_op.f("skills_name_key"), ["name"], postgresql_nulls_not_distinct=False
        )

    with op.batch_alter_table("shared_reports", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("shared_reports_user_id_fkey"), "users", ["user_id"], ["id"]
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            server_default=None,
            type_=postgresql.TIMESTAMP(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "recommendations",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            type_=postgresql.JSON(astext_type=sa.Text()),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "skills_at_time",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            type_=postgresql.JSON(astext_type=sa.Text()),
            existing_nullable=False,
        )

    with op.batch_alter_table("saved_jobs", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("saved_jobs_user_id_fkey"), "users", ["user_id"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("saved_jobs_job_id_fkey"), "jobs", ["job_id"], ["id"]
        )
        batch_op.drop_index(batch_op.f("ix_saved_jobs_job_id"))
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            server_default=None,
            type_=postgresql.TIMESTAMP(),
            existing_nullable=False,
        )

    with op.batch_alter_table("recommendation_history", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("recommendation_history_user_id_fkey"),
            "users",
            ["user_id"],
            ["id"],
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            server_default=None,
            type_=postgresql.TIMESTAMP(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "recommendations",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            type_=postgresql.JSON(astext_type=sa.Text()),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "skills_at_time",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            type_=postgresql.JSON(astext_type=sa.Text()),
            existing_nullable=False,
        )

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("jobs_company_id_fkey"), "companies", ["company_id"], ["id"]
        )
        batch_op.drop_index("ix_jobs_title_source")
        batch_op.drop_index(batch_op.f("ix_jobs_title"))
        batch_op.drop_index(batch_op.f("ix_jobs_source"))
        batch_op.drop_index(batch_op.f("ix_jobs_external_id"))
        batch_op.drop_index("ix_jobs_company_id")
        batch_op.create_unique_constraint(
            batch_op.f("jobs_external_id_key"),
            ["external_id"],
            postgresql_nulls_not_distinct=False,
        )

    with op.batch_alter_table("job_skills", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("job_skills_job_id_fkey"), "jobs", ["job_id"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("job_skills_skill_id_fkey"), "skills", ["skill_id"], ["id"]
        )

    # ### end Alembic commands ###
