"""index recommendation_history user_id and created_at

Revision ID: 24f2f1521727
Revises: 48c3d3c6a8da
Create Date: 2026-08-23 16:03:11.568540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f2f1521727'
down_revision: Union[str, Sequence[str], None] = '48c3d3c6a8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_recommendation_history_created_at'), 'recommendation_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendation_history_user_id'), 'recommendation_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_history_user_id'), table_name='recommendation_history')
    op.drop_index(op.f('ix_recommendation_history_created_at'), table_name='recommendation_history')
    # ### end Alembic commands ###
