"""add shared_reports table

Revision ID: 28527800a4eb
Revises: 389210b3aece
Create Date: 2026-08-23 16:49:36.254124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28527800a4eb'
down_revision: Union[str, Sequence[str], None] = '389210b3aece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_role', sa.String(), nullable=False),
    sa.Column('resolved_role', sa.String(), nullable=False),
    sa.Column('skills_at_time', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_reports_token'), 'shared_reports', ['token'], unique=True)
    op.create_index(op.f('ix_shared_reports_user_id'), 'shared_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_reports_user_id'), table_name='shared_reports')
    op.drop_index(op.f('ix_shared_reports_token'), table_name='shared_reports')
    op.drop_table('shared_reports')
    # ### end Alembic commands ###
