"""enforce unique company names

Revision ID: 389210b3aece
Revises: 565dff92a1cf
Create Date: 2026-08-23 16:24:47.615010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '389210b3aece'
down_revision: Union[str, Sequence[str], None] = '565dff92a1cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_companies_name', 'companies', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_companies_name', 'companies', type_='unique')
    # ### end Alembic commands ###
