"""add is_admin to users

Revision ID: 48303103e281
Revises: 28527800a4eb
Create Date: 2026-08-23 16:55:29.209993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48303103e281'
down_revision: Union[str, Sequence[str], None] = '28527800a4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand: autogenerate didn't include one, and
    # without it this fails against any DB that already has user rows
    # (NOT NULL column with no default can't be added to a populated table).
    # Existing rows get False (not admin) — the only safe default for a
    # brand-new authorization flag nothing has opted into yet.
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
