"""add tier to users

Revision ID: 4c46f32a6fda
Revises: 48303103e281
Create Date: 2026-08-23 16:58:47.169872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c46f32a6fda'
down_revision: Union[str, Sequence[str], None] = '48303103e281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand, same reason as the is_admin migration
    # right before this one: a bare NOT NULL column with no default fails
    # against a database that already has user rows. Existing users default
    # to "free" — nobody was ever on a paid tier before this column existed.
    op.add_column('users', sa.Column('tier', sa.String(), nullable=False, server_default='free'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tier')
    # ### end Alembic commands ###
