"""add unique constraint on job_skills job_id skill_id, drop redundant index

Revision ID: 565dff92a1cf
Revises: 229a42f618e2
Create Date: 2026-08-23 16:11:26.332488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '565dff92a1cf'
down_revision: Union[str, Sequence[str], None] = '229a42f618e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_skills_job_id'), table_name='job_skills')
    op.create_unique_constraint('uq_job_skills_job_id_skill_id', 'job_skills', ['job_id', 'skill_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_job_skills_job_id_skill_id', 'job_skills', type_='unique')
    op.create_index(op.f('ix_job_skills_job_id'), 'job_skills', ['job_id'], unique=False)
    # ### end Alembic commands ###
