"""index jobs on posted_date

Revision ID: 6e504270ae1e
Revises: 4c46f32a6fda
Create Date: 2026-08-23 19:06:29.815463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e504270ae1e'
down_revision: Union[str, Sequence[str], None] = '4c46f32a6fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_posted_date'), 'jobs', ['posted_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_posted_date'), table_name='jobs')
    # ### end Alembic commands ###
